### ISSUE TITLE
leetcode的作用

### ISSUE THREAD

**Issue by Lemonjing** [hongshibao/LeetCode#2]
刷leetcode找工作有用吗？

**Comment by hongshibao** [comment]
1. leetcode的题目主要是考察基础算法和编程能力。如果笔试或面试有环节是考察这方面能力的，用leetcode准备一下还是有点用的。
2. 有的人能通过做题培养出良好的思维方式、思考习惯、解决未知问题的能力，并且能够举一反三。这就类似于你在学校里学习数学一样，通过单纯学习概念和知识有时候并没法让你很好的掌握它们，但是通过做一些好的题目，也许能帮助你更深刻的掌握这些概念和知识，并了解如何运用这些知识去解决问题，当面对未知问题时，你也许就能很快地想到好的解决方案。大部分的人还是会觉得learning from example是更容易的。
3. 如果你能参与到一个好的工程项目，该项目同样能让你学习和巩固你的基础算法和编程能力，那么参与到该项目也是不错的选择。毕竟，刷leetcode题不是目的，公司招你过去还是主要希望你能在实际的工程项目中有活跃的表现。
4. 如果你没有机会参与到这种工程项目，那么刷题可能是比较好的辅助你找工作的训练方式。
5. 最后请记住，笔试面试时能力强的并不代表工作能力就一定强。二者很多时候是不match的。关键的是，你要让别人相信你是很有能力的，不管是在笔试面试还是以后工作中。从这个方面来看，我会觉得学习能力、思维习惯、责任心、积极性有时候是更重要的。

**Comment by Lemonjing** [comment]
## 笔试面试时能力强的并不代表工作能力就一定强。二者很多时候是不match的。
我喜欢这句话:)
